include ../../../quest_ext_vars.mk

MODULE_DIR = quest_gnc/src/diffeo
MODULE = $(subst /,,$(MODULE_DIR))

export BUILD_ROOT

include $(BUILD_ROOT)/mk/makefiles/module_targets.mk

# Add module specific targets here
